export const board = [
    [
        {piece: 'br', isAvailable: false},
        {piece: 'bk', isAvailable: false},
        {piece: 'bb', isAvailable: false},
        {piece: 'bq', isAvailable: false},
        {piece: 'bki', isAvailable: false},
        {piece: 'bb', isAvailable: false},
        {piece: 'bk', isAvailable: false},
        {piece: 'br', isAvailable: false},
    ],
    [
        {piece: 'bp', isAvailable: false},
        {piece: 'bp', isAvailable: false},
        {piece: 'bp', isAvailable: false},
        {piece: 'bp', isAvailable: false},
        {piece: 'bp', isAvailable: false},
        {piece: 'bp', isAvailable: false},
        {piece: 'bp', isAvailable: false},
        {piece: 'bp', isAvailable: false},
    ],
    [
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
    ],
    [
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
    ],
    [
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
    ],
    [
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
        {piece: '', isAvailable: false},
    ],
    [
        {piece: 'wp', isAvailable: false},
        {piece: 'wp', isAvailable: false},
        {piece: 'wp', isAvailable: false},
        {piece: 'wp', isAvailable: false},
        {piece: 'wp', isAvailable: false},
        // {piece: '', isAvailable: false},
        {piece: 'wp', isAvailable: false},
        {piece: 'wp', isAvailable: false},
        // {piece: '', isAvailable: false},
        {piece: 'wp', isAvailable: false},
        // {piece: '', isAvailable: false},
    ],
    [
        {piece: 'wr', isAvailable: false},
        {piece: 'wk', isAvailable: false},
        {piece: 'wb', isAvailable: false},
        {piece: 'wq', isAvailable: false},
        {piece: 'wki', isAvailable: false},
        {piece: 'wb', isAvailable: false},
        {piece: 'wk', isAvailable: false},
        {piece: 'wr', isAvailable: false},
    ],
]